FROM nginx:1.13.9

ARG STATIC_ANGULAR_HOSTNAME
ARG STATIC_ANGULAR_PORT
ARG STATIC_ANGULAR_PORTS

ENV STATIC_ANGULAR_HOSTNAME $STATIC_ANGULAR_HOSTNAME
ENV STATIC_ANGULAR_PORT $STATIC_ANGULAR_PORT
ENV STATIC_ANGULAR_PORTS $STATIC_ANGULAR_PORTS

COPY ./dist/ /usr/share/nginx/html/
