FROM nginx:1.13.9

ARG COMPONENT_PARAM_HOST
ARG COMPONENT_PARAM_LSTN
ARG COMPONENT_PARAM_PORT
ARG COMPONENT_PARAM_PORTS

ENV COMPONENT_PARAM_HOST $COMPONENT_PARAM_HOST
ENV COMPONENT_PARAM_LSTN $COMPONENT_PARAM_LSTN
ENV COMPONENT_PARAM_PORT $COMPONENT_PARAM_PORT
ENV COMPONENT_PARAM_PORTS $COMPONENT_PARAM_PORTS

COPY ./dist/ /usr/share/nginx/html/
