FROM nginx:1.13.9

ARG PROJECT_PARAM_HOST
ARG PROJECT_PARAM_LSTN
ARG PROJECT_PARAM_PORT
ARG PROJECT_PARAM_PORTS

ENV PROJECT_PARAM_HOST $PROJECT_PARAM_HOST
ENV PROJECT_PARAM_LSTN $PROJECT_PARAM_LSTN
ENV PROJECT_PARAM_PORT $PROJECT_PARAM_PORT
ENV PROJECT_PARAM_PORTS $PROJECT_PARAM_PORTS

COPY ./dist/ /usr/share/nginx/html/
